### ISSUE TITLE
LinkTimeout randomly ignored

### ISSUE THREAD

**Issue by desbma** [tokio-rs/io-uring#156] opened 2022-11-09 17:04 UTC
I have noticed in my program, that when adding a `LinkTimeout` operation after a `Connect`, sometimes (randomly) the timeout is ignored and the connect operation blocks forever.

**It seems to occur more frequently when the binary is compiled in release mode.**

I have made a minimal program, which allows me to reproduce 100% of the time (run with `cargo run --release`), the program should not block more that 3 seconds, but it does:

`Cargo.toml`:
```toml
[package]
name = "io_uring_test"
version = "0.1.0"
edition = "2021"

[dependencies]
io-uring = "0.5.9"
nix = { version = "0.25.0", default-features = false, features = ["net", "socket"] }
```

`src/main.rs`:
```rust
use io_uring::{
    opcode, squeue,
    types::{Fd, Timespec},
    IoUring,
};
use nix::sys::socket::{socket, AddressFamily, SockFlag, SockType, SockaddrIn, SockaddrLike};

fn main() {
    let mut ring = IoUring::new(8).unwrap();

    let sckt = socket(
        AddressFamily::Inet,
        SockType::Stream,
        SockFlag::empty(),
        None,
    )
    .unwrap();
    let addr = SockaddrIn::new(37, 187, 0, 1, 80);  // an IP that does not respond

    let op_connect = opcode::Connect::new(Fd(sckt), addr.as_ptr(), addr.len())
        .build()
        .flags(squeue::Flags::IO_LINK)
        .user_data(1);

    let op_connect_timeout = opcode::LinkTimeout::new(&Timespec::new().sec(3))
        .build()
        .user_data(2);

    let ops = [op_connect, op_connect_timeout];

    eprintln!("{ops:?}");

    for op in &ops {
        unsafe {
            ring.submission().push(op).unwrap();
        }
    }

    ring.submit_and_wait(2).unwrap();
}

```

EDIT: removed use of `unsafe` feature flag.

**Comment by FrankReh** [comment] 2022-11-09 17:40
Maybe put the link on the timeout op and submit that first?

**Comment by desbma** [comment] 2022-11-09 18:11
No the LINK_TIMEOUT should follow the entry it is related to.

> The way to use then is to setup your command as you usually would, but then
mark is IOSQE_IO_LINK and add an IORING_OP_LINK_TIMEOUT right after it.

https://lore.kernel.org/io-uring/a35ad645-0340-62e4-fba7-7c1a080a9a65@kernel.dk/t/

If I reverse the order the LinkTimeout completion entry has -EINVAL error.

**Comment by desbma** [comment] 2022-11-09 18:14
The issue is also reproducible with a read on a TCP socket, and everything works fine in my io_uring program (connect, read fixed, write fixed, close...) apart from the LinkTimeout entries that have no effect most of the time.

**Comment by desbma** [comment] 2022-11-09 18:21
I also tried the following:
- creating the socket with O_NONBLOCK
- using the ASYNC flag for the Connect op
- setting an absolute time in Timespec and using the ABS flag

None of that had any effect. Also weird: the program blocks for 210s, when the kernel default TCP timeout is 60s.

**Comment by Noah-Kennedy** [comment] 2022-11-09 18:42
Which kernel version is this btw?

**Comment by FrankReh** [comment] 2022-11-09 19:27
BTW, the reproducer from above works on my Linux machine. Times out after the desired number of seconds. I'm on

Linux nuc 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Noah-Kennedy** [comment] 2022-11-09 20:16
I'm on `6.0.7`. I'll try and repo later tonight or tomorrow.

**Comment by Noah-Kennedy** [comment] 2022-11-09 20:18
Reason why I'm wondering about the kernel is that there were a _lot_ of issues fixed in `6.0`.

We might wanna do some work first here to see what is getting submitted to the kernel. I'm kinda wondering rn if this is a timing issue in uring that is being exacerbated by release mode being faster or if this is a soundness issue in this crate.

**Comment by desbma** [comment] 2022-11-09 21:25
> Which kernel version is this btw?

6.0.7 (Debian Sid)

**Comment by FrankReh** [comment] 2022-11-10 04:14
The problem is with the op type definition. It takes a pointer to a Timespec, not a struct.
The reason it works in debug I bet is the stack frame isn't optimized to reuse space, so the data for the Timespec could live in the frame long enough for the driver to read it. In release mode, the frame's local variables are given space just long enough for the required lifetime (or so I've read).

```rust
    let op_connect_timeout = opcode::LinkTimeout::new(&Timespec::new().sec(3))
```
You can work around the problem easily by defining a new local for the Timespec with a scope that will outlast the request
and then pass the address of the local to the new call.
```rust
    let ts = Timespec::new().sec(2);
    let op_connect_timeout = opcode::LinkTimeout::new(&ts)
```

**Comment by FrankReh** [comment] 2022-11-10 04:16
Are unit tests run in debug or release mode I wonder.

**Comment by FrankReh** [comment] 2022-11-10 04:17
BTW, I like having this small program for a linked pair of ops. It will come in very handy. Thank you.

**Comment by desbma** [comment] 2022-11-10 08:52
Thanks @FrankReh, that was indeed the cause of my issue.

I'm closing this then, since the issue is in my program.

I think the API is easy to misuse though, which is unusual for Rust, but I guess it is the price to pay when using low level bindings.

Thanks again

**Comment by FrankReh** [comment] 2022-11-10 14:22
I think we've run into this problem before where even an experienced rust and tokio developer fell into the same trap and the code existed in one of their crates for a long time. I wondered then why there wasn't an unsafe required to alert the caller they were doing something that was easy to misuse.

Turns out there was then, and there is in your small reproducer too but you didn't notice the warning that came with the unsafe use, and Noah didn't, and I didn't.

Where the reproducer uses unsafe, it does so because the *push* onto the submission queue is unsafe. And the Safety warning in that push documentation says "Developers must ensure that parameters of all the entries are valid and will be valid for the entire duration of the operation." (With a little paraphrasing of my own.)

My point isn't that the problem was yours, but that the problem is with this crate or the warning or our complacency with using unsafe. Again, because a very experienced tokio person made this same mistake, and many of us read through that code many times and it didn't strike us, and you fell into it here, and a couple of us looked at your 42 lines of code and it didn't strike us immediately either.

Something should be changed. Maybe the *push* should be renamed to something like *unsafe_push* or *really_unsafe_push*. Maybe someone else can chime in with a better idea.

Your case pointed out another nasty aspect of this kind of bug. It can go undetected when running in debug mode. And in release mode, a problem can occur, and the kernel won't even know it was given wrong data sometimes so won't respond with an error. So all the stress testing, theoretically, done in debug mode doesn't help catch this.

I'm going to reopen this so @Noah-Kennedy and @quininer can give this a think too.
Thanks.

**Comment by desbma** [comment] 2022-11-10 14:41
I totally agree with you.

To give some context, I had a similar issue with the socket address and the Connect operation. But in this case the explicit `.as_ptr()` made me quickly notice and fix the issue.

With the Timespec, i missed that what is passed is a pointer a not a `&Timespec`, that is why I didn't realize it has to outlive the submit call.

**Comment by FrankReh** [comment] 2022-11-10 14:56
I know taking an address isn't considered unsafe and that's why the *new* functions like for Connect and LinkTimeout aren't unsafe, but I've wondered if they and other op code's that use pointers should be made unsafe.

Or could a reference with a bounded lifetime  be used as input to *new* rather than a const pointer and could the borrow-checker be asked to guarantee consistency until the *enter* syscall is made by the submit (or submit_and_wait in this case).
I suspect not, and some kernel structures passed are a deeper tree of allocated memory so the lifetime of the top level isn't going to be stringent enough anyway.

**Comment by FrankReh** [comment] 2022-11-10 14:59
And I can't think of a runtime check, made in debug mode, that even checks for the lifetime of pointed to data that we could built into the SQ push.

**Comment by desbma** [comment] 2022-11-10 15:04
> Or could a reference with a bounded lifetime be used as input to new rather than a const pointer and could the borrow-checker be asked to guarantee consistency until the enter syscall is made by the submit (or submit_and_wait in this case).

I think it would definitely be the most Rust idiomatic way to do it. I'm not a Rust expert but I think to do that you would have to completely change the API, to consume whatever object hold the reference at the submit call.

**Comment by quininer** [comment] 2022-11-10 15:36
I thought about this issue critically when designing the API and concluded that I couldn't guarantee it in low-level API. build a high-level API around it is best way to go.

**Comment by FrankReh** [comment] 2022-11-10 16:14
Folks keep trying to use the io-crate like it was a stand alone library to build an app off of.

**Comment by FrankReh** [comment] 2022-11-10 16:48
Okay. I'm going to close. I know @Noah-Kennedy doesn't have time to rethink things at this level. I'll let the issue drop.

**Closed by FrankReh** 2022-11-10 16:48 UTC

**Comment by Noah-Kennedy** [comment] 2022-11-10 18:23
@FrankReh Don't worry about what I have time for, I can get back to thinks later.

IMO this isn't the right place to add these types of semantics. Doing this would basically require us to move the reactor from tokio-uring into here, and I don't think that this is a good idea. The reactor should be a part of async runtimes leveraging this, and they should be responsible for maintaining lifetime invariants here.

I think that the issue here is that historically tokio-uring wasn't always in the nicest spot, but I feel like this is changing now as we've been doing a lot of work to bring it closer to feature parity. `tokio-uring` should be what folks are using who aren't writing their own async runtime around this.
